api:
    type:       rest
    prefix:     /api/v1
    resource:   '@ApiBundle/Resources/config/routes.yml'

fos_user_security:
    resource: '@FOSUserBundle/Resources/config/routing/security.xml'
    prefix: /api/v1

NelmioApiDocBundle:
    resource:   '@NelmioApiDocBundle/Resources/config/routing.yml'
    prefix:     /api/v1/doc